package com.example.Bookstore.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity // Entity class corresponds with database table / Luokka on entiteetti-luokka (Oletetaan että tietokannassa on vastaavan niminen taulu)
public class Book {
@Id	//Unique id for database
@GeneratedValue(strategy=GenerationType.AUTO) //unique id automatically generated by database
private long id;
private String title;
private String author;
private int bookYear;
private String isbn;
private double price;

public Book() {
	super();
}

public Book(String title, String author, int year, String isbn, double price) {
	super();
	this.title = title;
	this.author = author;
	this.bookYear = bookYear;
	this.isbn = isbn;
	this.price = price;
}


public long getId() {
	return id;
}

public void setId(long id) {
	this.id = id;
}

public int getBookYear() {
	return bookYear;
}

public void setBookYear(int bookYear) {
	this.bookYear = bookYear;
}

public String getTitle() {
	return title;
}
public void setTitle(String title) {
	this.title = title;
}
public String getAuthor() {
	return author;
}
public void setAuthor(String author) {
	this.author = author;
}
public int getbookYear() {
	return bookYear;
}
public void setbookYear(int bookYear) {
	this.bookYear = bookYear;
}
public String getIsbn() {
	return isbn;
}
public void setIsbn(String isbn) {
	this.isbn = isbn;
}
public double getPrice() {
	return price;
}
public void setPrice(double price) {
	this.price = price;
}

@Override
public String toString() {
	return "Book [id=" + id + ", title=" + title + ", author=" + author + ", bookYear=" + bookYear + ", isbn=" + isbn
			+ ", price=" + price + "]";
}



}
